name: Build and Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate manifest.json
      run: |
        cd src
        if ! python -c "import json; json.load(open('manifest.json'))" 2>/dev/null; then
          echo "manifest.json is not valid JSON"
          exit 1
        fi
        echo "manifest.json is valid JSON"

    - name: Check required files
      run: |
        cd src
        required_files=(
          "manifest.json"
          "core/background.js"
          "ui/popup.html"
          "ui/icons/icon16.png"
          "ui/icons/icon48.png"
          "ui/icons/icon128.png"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Required file missing: $file"
            exit 1
          fi
        done
        echo "All required files are present"

    - name: Test build process
      run: |
        mkdir -p build
        cp -r src/* build/
        cd build
        zip -r ../test-extension.zip .
        echo "Build process completed successfully"
        ls -la ../test-extension.zip